// GENERATED by scripts/gen_companion_art.sh. Do not edit by hand.

import 'dart:ui';

/// Pixel size of every bundled companion image ({species}_{c|r|e|l}).
const Map<String, Size> companionArt = {
  'brine_c': Size(720, 509),
  'brine_r': Size(720, 560),
  'coil_c': Size(614, 720),
  'coil_e': Size(720, 626),
  'dune_c': Size(720, 595),
  'dune_l': Size(679, 720),
  'gilt_c': Size(720, 719),
  'gilt_l': Size(706, 720),
  'gilt_r': Size(720, 693),
  'glaze_c': Size(720, 664),
  'hookfin_c': Size(720, 568),
  'hookfin_l': Size(720, 605),
  'lumen_c': Size(720, 601),
  'lumen_r': Size(549, 720),
  'pebble_c': Size(720, 442),
  'pebble_l': Size(720, 545),
  'pebble_r': Size(720, 588),
  'valve_c': Size(720, 557),
  'valve_r': Size(720, 608),
  'vine_c': Size(720, 583),
  'vine_e': Size(720, 491),
  'vine_r': Size(720, 645),
};

/// Transparent border around the trimmed creature, in image pixels.
const double companionArtBorder = 12;
