// GENERATED by scripts/gen_companion_art.sh. Do not edit by hand.

import 'dart:ui';

/// Pixel size of every bundled companion image ({species}_{c|r|e|l}).
const Map<String, Size> companionArt = {
  'brine_c': Size(720, 509),
  'coil_c': Size(614, 720),
  'dune_c': Size(720, 595),
  'gilt_c': Size(720, 719),
  'gilt_l': Size(706, 720),
  'gilt_r': Size(720, 693),
  'glaze_c': Size(720, 664),
  'hookfin_c': Size(720, 568),
  'lumen_c': Size(720, 601),
  'pebble_c': Size(720, 442),
  'valve_c': Size(720, 557),
  'vine_c': Size(720, 583),
};

/// Transparent border around the trimmed creature, in image pixels.
const double companionArtBorder = 12;
