// GENERATED by scripts/gen_boot_footprints.sh. Do not edit by hand.

import 'dart:ui';

/// Opaque bounds of each boot image as fractions of the image size.
const Map<String, Rect> bootFootprints = {
  'boot_01': Rect.fromLTRB(0.207, 0.185, 0.740, 0.817),
  'boot_02': Rect.fromLTRB(0.205, 0.180, 0.773, 0.752),
  'boot_03': Rect.fromLTRB(0.199, 0.166, 0.781, 0.803),
  'boot_04': Rect.fromLTRB(0.172, 0.276, 0.822, 0.734),
  'boot_05': Rect.fromLTRB(0.129, 0.201, 0.859, 0.746),
  'boot_06': Rect.fromLTRB(0.203, 0.211, 0.797, 0.781),
  'boot_07': Rect.fromLTRB(0.148, 0.244, 0.842, 0.744),
  'boot_08': Rect.fromLTRB(0.143, 0.224, 0.848, 0.749),
  'boot_09': Rect.fromLTRB(0.146, 0.180, 0.822, 0.791),
  'boot_10': Rect.fromLTRB(0.148, 0.234, 0.852, 0.763),
  'boot_11': Rect.fromLTRB(0.227, 0.188, 0.773, 0.770),
  'boot_12': Rect.fromLTRB(0.158, 0.178, 0.810, 0.793),
  'boot_13': Rect.fromLTRB(0.164, 0.161, 0.826, 0.803),
  'boot_15': Rect.fromLTRB(0.180, 0.143, 0.830, 0.799),
  'boot_16': Rect.fromLTRB(0.172, 0.113, 0.797, 0.842),
  'boot_17': Rect.fromLTRB(0.195, 0.123, 0.779, 0.825),
  'boot_18': Rect.fromLTRB(0.190, 0.190, 0.807, 0.732),
  'boot_19': Rect.fromLTRB(0.143, 0.158, 0.830, 0.805),
  'boot_20': Rect.fromLTRB(0.154, 0.146, 0.848, 0.805),
  'boot_22': Rect.fromLTRB(0.201, 0.219, 0.781, 0.750),
  'boot_23': Rect.fromLTRB(0.224, 0.143, 0.724, 0.838),
  'boot_25': Rect.fromLTRB(0.141, 0.160, 0.838, 0.791),
  'boot_26': Rect.fromLTRB(0.162, 0.193, 0.842, 0.779),
  'boot_27': Rect.fromLTRB(0.153, 0.205, 0.848, 0.776),
  'boot_29': Rect.fromLTRB(0.156, 0.152, 0.834, 0.779),
  'boot_30': Rect.fromLTRB(0.182, 0.191, 0.795, 0.779),
  'boot_32': Rect.fromLTRB(0.143, 0.211, 0.862, 0.763),
  'boot_33': Rect.fromLTRB(0.121, 0.219, 0.881, 0.770),
  'boot_34': Rect.fromLTRB(0.123, 0.059, 0.844, 0.886),
  'boot_35': Rect.fromLTRB(0.201, 0.180, 0.786, 0.820),
  'boot_36': Rect.fromLTRB(0.162, 0.199, 0.830, 0.771),
  'boot_37': Rect.fromLTRB(0.113, 0.161, 0.896, 0.781),
  'boot_38': Rect.fromLTRB(0.209, 0.153, 0.807, 0.825),
  'boot_39': Rect.fromLTRB(0.151, 0.130, 0.849, 0.832),
  'boot_40': Rect.fromLTRB(0.188, 0.076, 0.797, 0.838),
};

/// Fallback for images without a generated entry.
const Rect defaultBootFootprint = Rect.fromLTRB(0.17, 0.17, 0.83, 0.8);
