#!/usr/bin/env bash
# Regenerates lib/domain/boot_footprint.dart from the opaque bounds of assets/boots/*.png.
# Requires ImageMagick. Run after adding or editing boot images.
set -euo pipefail
cd "$(dirname "$0")/.."
out=lib/domain/boot_footprint.dart
{
  echo '// GENERATED by scripts/gen_boot_footprints.sh. Do not edit by hand.'
  echo
  echo "import 'dart:ui';"
  echo
  echo '/// Opaque bounds of each boot image as fractions of the image size.'
  echo 'const Map<String, Rect> bootFootprints = {'
  for f in assets/boots/*.png; do
    id=$(basename "$f" .png)
    read -r W H <<<"$(identify -format '%w %h' "$f")"
    geo=$(convert "$f" -alpha extract -threshold 50% -format '%@' info:)
    read -r w h x y <<<"$(echo "$geo" | sed -E 's/([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)/\1 \2 \3 \4/')"
    awk -v id="$id" -v W="$W" -v H="$H" -v w="$w" -v h="$h" -v x="$x" -v y="$y" \
      'BEGIN { printf "  \x27%s\x27: Rect.fromLTRB(%.3f, %.3f, %.3f, %.3f),\n", id, x/W, y/H, (x+w)/W, (y+h)/H }'
  done
  echo '};'
  echo
  echo '/// Fallback for images without a generated entry.'
  echo 'const Rect defaultBootFootprint = Rect.fromLTRB(0.17, 0.17, 0.83, 0.8);'
} > "$out"
dart format "$out" >/dev/null
