#!/usr/bin/env bash
# Regenerates lib/data/companion_art.dart from assets/companions/*.png.
# Requires ImageMagick. Run after adding or editing companion images.
set -euo pipefail
cd "$(dirname "$0")/.."
out=lib/data/companion_art.dart
{
  echo '// GENERATED by scripts/gen_companion_art.sh. Do not edit by hand.'
  echo
  echo "import 'dart:ui';"
  echo
  echo '/// Pixel size of every bundled companion image ({species}_{c|r|e|l}).'
  echo 'const Map<String, Size> companionArt = {'
  for f in assets/companions/*.png; do
    id=$(basename "$f" .png)
    read -r W H <<<"$(identify -format '%w %h' "$f")"
    echo "  '$id': Size($W, $H),"
  done
  echo '};'
  echo
  echo '/// Transparent border around the trimmed creature, in image pixels.'
  echo 'const double companionArtBorder = 12;'
} > "$out"
dart format "$out" >/dev/null
